runtime: nodejs
env: flex
env_variables:
  PG_USER: postgres
  PG_PASSWORD: sunway123
  PG_DATABASE: cem
  PG_INSTANCE_NAME: cem-server-production:asia-northeast1:cem-server-production
beta_settings:
  cloud_sql_instances: cem-server-production:asia-northeast1:cem-server-production
