runtime: nodejs
vm: true
env: flex
# [START network]
# This ensures clients will be able to connect via websockets to any instance of
# this app using websockets
network:
  forwarded_ports:
  - 65080
  instance_tag: websocket
# [END network]
env_variables:
  PG_USER: postgres
  PG_PASSWORD: sunway123
  PG_DATABASE: cem
  PG_INSTANCE_NAME: cem-server-production:asia-northeast1:cem-server-production
  JWT_SECRET: aksdjqopwieopqiw;dalskdl;askdas
  JWT_REFRESH_SECRET: alksdjoiouqwedASDASDA1231232
beta_settings:
  cloud_sql_instances: cem-server-production:asia-northeast1:cem-server-production
# [END app_yaml]
