const paperReview = [
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 1,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 2,
    content: 'no content',
    point: 4,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 3,
    content: 'no content',
    point: 5,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 4,
    content: 'no content',
    point: 2,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 2,
    review_question_id: 1,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 2,
    review_question_id: 2,
    content: 'no content',
    point: 4,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 2,
    review_question_id: 3,
    content: 'no content',
    point: 5,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 2,
    review_question_id: 4,
    content: 'no content',
    point: 2,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 5,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 6,
    content: 'no content',
    point: 5,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 7,
    content: 'no content',
    point: 1,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 1,
    review_question_id: 8,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 1,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 3,
    review_question_id: 5,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 3,
    review_question_id: 6,
    content: 'no content',
    point: 5,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 3,
    review_question_id: 7,
    content: 'no content',
    point: 1,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 3,
    paper_id: 3,
    review_question_id: 8,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 3,
    review_question_id: 1,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 2,
    content: 'no content',
    point: 4,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 3,
    content: 'no content',
    point: 5,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 4,
    content: 'no content',
    point: 2,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 5,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 6,
    content: 'no content',
    point: 5,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 7,
    content: 'no content',
    point: 1,
    comment: 'no comment',
  },
  {
    conference_id: 1,
    user_id: 4,
    paper_id: 1,
    review_question_id: 8,
    content: 'no content',
    point: 3,
    comment: 'no comment',
  },
];

module.exports = paperReview;
